execute pathogen#infect()

" " --- vundle setup -------------------------------------------------------------
" set nocompatible              " be iMproved, required
" filetype off                  " required
" 
" set rtp+=~/.vim/bundle/vundle/
" call vundle#rc()
" 
" Bundle 'gmarik/vundle'
" Bundle 'tpope/vim-sensible'
" Bundle 'scrooloose/nerdtree'
" Bundle 'taglist.vim'
" 
" filetype plugin indent on     " required
" " ------------------------------------------------------------------------------

if has('gui_running')
    colorscheme slate

    set guioptions-=m " remove menu bar
    set guioptions-=T " remove toolbar
    set guioptions-=r " remove right-hand scroll bar
    set guioptions-=L " remove left-hand scroll bar
    " toggle menu bar with <c-f1>
    nnoremap <C-F1> :if &go=~#'m'<Bar>set go-=m<Bar>else<Bar>set go+=m<Bar>endif<CR>
else
    colorscheme default
endif

if has('win32')
    set guifont=Consolas:h10:cANSI
endif

set tabstop=4
set shiftwidth=4

" allow edited files to be put in the background
set hidden

" make tab characters visible
set list

" turn on number and relativenumber
set number
set relativenumber

" turn on search result hightlighting
set hlsearch

" configure taglist
if has('win32')
    " let taglist find the ctags executable
    let Tlist_Ctags_Cmd = 'C:\Users\soconnel\Applications\ctags58\ctags.exe'
endif
let Tlist_Use_Right_Window = 1

" look for tags file in parent directories
"set tags=./tags,tags,../../tags

set visualbell

let mapleader = "-"
let maplocalleader = "\\"
nnoremap <leader>el :execute getline('.')<cr>
nnoremap <leader>cl :let @l=expand('%:p') . ":" . line('.') . "\n -> " . getline('.') . "\n\n"<cr>
nnoremap <leader>ev :e $MYVIMRC<cr>
nnoremap <leader>sv :so $MYVIMRC<cr>
nnoremap <leader>w- O<esc>80i-<esc>j^
" use ctrl-^ from now on
" nnoremap <leader>bl :b#<cr>
nnoremap <leader>se :resize 34<cr>
nnoremap <leader>tl :TlistToggle<cr>
nnoremap <leader>hl :nohlsearch<cr>
nnoremap <leader>msg O::msg_vdebug("shane: 
nnoremap <c-j> 3<c-e>
nnoremap <c-k> 3<c-y>

"nnoremap <silent><a-o> :set paste<CR>m`o<Esc>``:set nopaste<CR>
nnoremap <silent><leader>o :set paste<CR>m`O<Esc>``:set nopaste<CR>

if has('win32')
	nnoremap <leader>nt :NERDTree D:\work<cr>
	nnoremap <leader>ct :ConqueTerm C:\Windows\System32\cmd.exe /k S:\tools\acds_bri\arc_shortcut.bat<cr>
	nnoremap <leader>en :e X:\work\notes.txt<cr>
else
	nnoremap <leader>nt :NERDTree /data/soconnel/work<cr>
	nnoremap <leader>ct :ConqueTerm bash<cr>
	nnoremap <leader>en :e /data/soconnel/work/notes.txt<cr>
endif

" use `w to control window stuff instead of <c-w>
nnoremap `w <c-w>
nnoremap <c-w> <nop>

" nnoremap `k <c-e>
" nnoremap `j <c-y>

" use ; instead of : to do ex commands
" nnoremap ; :
" nnoremap : <nop>

" use ;; for ; and ,, for , since I use them for : and <leader>
" nnoremap ;; ;
" nnoremap ,, ,

" use jj instead of <esc> to exit insert/visual mode
inoremap jk <esc>
vnoremap jk <esc>

" always show a list of tags if more than one is found
nnoremap <c-]> g<c-]>

set colorcolumn=81
if has('gui_running')
    highlight ColorColumn ctermbg=black guibg=black
endif

" fix tab completion to make sense
set wildmode=longest,list,full
