execute pathogen#infect()

if has('gui_running')
    colorscheme slate

    set guioptions-=m " remove menu bar
    set guioptions-=T " remove toolbar
    set guioptions-=r " remove right-hand scroll bar
    set guioptions-=L " remove left-hand scroll bar
    " toggle menu bar with <c-f1>
    nnoremap <C-F1> :if &go=~#'m'<Bar>set go-=m<Bar>else<Bar>set go+=m<Bar>endif<CR>
else
    colorscheme desert
endif

if has('win32')
    set guifont=Consolas:h10:cANSI
endif

set tabstop=4
set shiftwidth=4

" allow edited files to be put in the background
set hidden

" make tab characters visible
set list

" turn on number and relativenumber
set number
set relativenumber

" turn on search result hightlighting
set hlsearch

" turn on folding using syntax
set foldmethod=syntax

" configure taglist
if has('win32')
    " let taglist find the ctags executable
    let Tlist_Ctags_Cmd = 'C:\Users\soconnel\Applications\ctags58\ctags.exe'
    let g:ctrlp_buftag_ctags_bin = 'C:\Users\soconnel\Applications\ctags58\ctags.exe'
else
    let Tlist_Ctags_Cmd = '/home/soconnel/bin/ctags/bin/ctags'
    let g:ctrlp_buftag_ctags_bin = '/home/soconnel/bin/ctags/bin/ctags'
endif
" let Tlist_Use_Right_Window = 1

" configure ctrlp
let g:ctrlp_extensions = ['undo', 'line', 'mixed', 'buffertag']
let g:ctrlp_cmd = 'CtrlPMRU'

set visualbell

let mapleader = "\<space>"
let maplocalleader = "\\"
nnoremap <leader>el :execute getline('.')<cr>
nnoremap <leader>cl :let @l=expand('%:p') . ":" . line('.') . "\n -> " . getline('.') . "\n\n"<cr>
nnoremap <leader>ev :e $MYVIMRC<cr>
nnoremap <leader>sv :so $MYVIMRC<cr>
nnoremap <leader>w- O<esc>80i-<esc>j^
nnoremap <leader>tl :TlistToggle<cr>
nnoremap <leader>hl :nohlsearch<cr>
nnoremap <leader>msg O::msg_vdebug("shane: 
nnoremap <c-j> 4<c-e>
nnoremap <c-k> 4<c-y>
nnoremap <a-j> 10j
nnoremap <a-k> 10k

" map <leader>f <Plug>(easymotion-f)
map <leader>f <Plug>(easymotion-bd-f)
map <leader>F <Plug>(easymotion-F)
map <leader>t <Plug>(easymotion-t)
map <leader>T <Plug>(easymotion-T)
" map <leader>w <Plug>(easymotion-bd-w)
map <leader>w <Plug>(easymotion-w)
map <leader>W <Plug>(easymotion-W)
map <leader>b <Plug>(easymotion-b)
map <leader>B <Plug>(easymotion-B)
map <leader>j <Plug>(easymotion-j)
map <leader>k <Plug>(easymotion-k)
map <leader>ma <Plug>(easymotion-jumptoanywhere)

" use [<space> and ]<space> from unimpaired instead
"nnoremap <silent><a-o> :set paste<CR>m`o<Esc>``:set nopaste<CR>
"nnoremap <silent><leader>o :set paste<CR>m`O<Esc>``:set nopaste<CR>

if has('win32')
	nnoremap <leader>cdw :cd D:\work<cr>
	nnoremap <leader>nt :NERDTree D:\work<cr>
	nnoremap <leader>ct :ConqueTerm C:\Windows\System32\cmd.exe /k S:\tools\acds_bri\arc_shortcut.bat<cr>
else
	nnoremap <leader>cdw :cd /data/soconnel/work<cr>
	nnoremap <leader>nt :NERDTree /data/soconnel/work<cr>
	nnoremap <leader>ct :ConqueTerm bash<cr>
endif

" use `w to control window stuff instead of <c-w>
nnoremap `w <c-w>
nnoremap <c-w> <nop>

" use jk to exit insert/visual mode
inoremap jk <esc>
vnoremap jk <esc>

" always show a list of tags if more than one is found
nnoremap <c-]> g<c-]>

set colorcolumn=81
if has('gui_running')
    highlight ColorColumn ctermbg=black guibg=black
endif

" fix tab completion to make sense
set wildmode=longest,list,full
