alias ls='ls -Fh --color=auto'
alias la='ls -Fha --color=auto'
alias ll='ls -Fhl --color=auto'
alias lla='ls -Fhla --color=auto'
alias ltr='ls -Fhltr --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
