alias ls='ls -Fh --color=auto'
alias la='ls -FhA --color=auto'
alias lA='ls -Fha --color=auto'
alias ll='ls -Fhl --color=auto'
alias lla='ls -FhlA --color=auto'
alias llA='ls -Fhla --color=auto'
alias ltr='ls -Fhltr --color=auto'
alias latr='ls -Fhltar --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'

alias b='cd ${OLDPWD}'
